from bot_db import *

def fill_db(fw, nw, ex):
    topic="renovation"
    c=open_db()
    c.execute("INSERT OR IGNORE INTO word_set (f_word, f_lang, f_example, topic, tr1_lang, tr1) VALUES (?, 'en', ?, ?, 'ru', ?)", (fw, ex, topic, nw))
    close_db(True)

def change_db(fw, new_nw):
    c=open_db()
    c.execute(f"UPDATE word_set SET tr1 = ? WHERE f_word = ?",  (new_nw, fw))
    close_db(True)

fill_db("caulk", "герметик, шпаклевка для швов", "I bought a caulk to seal the gaps in the bathroom tiles.")
fill_db("AAC blocks", "газобетонный блок", "What thickness of plaster will be applied to the new wall made of AAC blocks?")
fill_db("a grout", "затирка для плитки", "Could you please confirm the color of the grout we'll be using for the tile joints in the bathroom?")
fill_db("three-way switch", "проходной выключатель", "We're planning to install a three-way switch for the hallway lights. Is it possible?")
fill_db("foreman", "прораб", "The foreman hasn't been on the site for the past four days.")
fill_db("radiator", "Батарея отопления", "When is the deadline to install the new radiators?")
fill_db("shower pan", "душевой поддон", "The installation of the shower pan is complete, and we're ready to proceed with tiling the shower area.")
fill_db("soundproofing", "звукоизоляция", "We're considering adding additional soundproofing to the walls.")
fill_db("tile installation", "укладка плитки", "The tile installation in the kitchen is progressing well, and we'll move on to the bathroom next.")
fill_db("plastering", "нанесение штукатурки", "The bathroom has good wall geometry with AAC blocks. We will lay the tiles without plastering.")
fill_db("plasterer", "штукатур", "The plasterer is scheduled to start working on the ceiling repairs tomorrow.")
fill_db("crown molding", "карниз", "The foreman said that he has run out of special glue for crown moldings.")
fill_db("drywall", "гкл", "We have 5 sheets of drywall left. We can try to build the structure you were talking about.")
fill_db("load-bearing", "несущий (напр. стена)", "This is a load-bearing wall, and it's not possible to create niches within it.")
fill_db("floor screed", "стяжка пола", "How many days will the floor screed need to dry?")
fill_db("recessed", "встроенный", "We're planning to install recessed lighting in the ceiling with GX-53 sockets.")
fill_db("surface-mounted", "накладной", "This light fixture is surface-mounted; its instruction manual is included in the box.")
fill_db("recessed wall niche", "ниша в стене", "And please, don't forget, we're planning to create a recessed wall niche on this particular wall.")
fill_db("concealed wiring", "скрытая проводка", "If we install a speaker bracket here, will we not damage the concealed wiring?")
fill_db("sockets installation", "установка розеток", "We're almost done with the sockets installation in the kitchen; just a few more to go.")
fill_db("to redo", "переделать", "The tile installation doesn't match the flooring layout plan. You need to redo it.")
fill_db("baseboard", "плинтус", "How should the baseboard meet the door casing?")
fill_db("lighting fixtures", "осветительные приборы", "All the lighting fixtures have been ordered, and the delivery is scheduled for Friday.")
fill_db("plumbing", "водопровод и канализация", "I hope that replacing the bathtub with a new one won't require any plumbing work.")
fill_db("faucet", "водопроводный кран", "It seems, the plumber accidentally switched the faucet models between the bathroom and the restroom.")
fill_db("sink", "раковина", "Unfortunately, the sink arrived with a crack. The supplier has assured us they will replace it tomorrow.")
fill_db("flooring", "покрытие пола", "Does your budget allow for hardwood flooring at least in this area?")
fill_db("renovation", "ремонт", "Our apartment renovation was completed on time! I believe it's not just luck but also due to having a well-defined plan.")
fill_db("completion deadline", "срок окончания работ", "The completion deadline has passed, but the foreman promises to finish within 3 days.")
fill_db("stripping out", "демонтаж",  "Before starting the renovation, we'll need to do a complete stripping out of the old interior")
fill_db("Author's supervision", "авторский надзор", "We really don't want to deal with the foreman every day and handle a bunch of his queries. We're in need of Author's supervision.")